[features]
seeds = false
skip-lint = false
[programs.devnet]
s_stacking = "AuCtWxqpFjNhHzNBJ831c7TEkwG2FQyB4G7hAsyatcMt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "test-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/s-stacking.ts"
